# Generated by Django 2.2.4 on 2019-12-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20191229_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='_timezone',
            field=models.IntegerField(null=True, verbose_name='Timezone'),
        ),
    ]
