# Generated by Django 2.2.4 on 2019-12-30 00:35

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20191229_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), geography=True, srid=4326),
        ),
    ]
