# Generated by Django 2.2.4 on 2019-12-28 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('disambiguation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('arid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('artist', models.TextField(blank=True, null=True)),
                ('artistaccent', models.TextField(blank=True, null=True)),
                ('begin', models.TextField(blank=True, null=True)),
                ('beginarea', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('end', models.TextField(blank=True, null=True)),
                ('endarea', models.TextField(blank=True, null=True)),
                ('ended', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('ipi', models.TextField(blank=True, null=True)),
                ('sortname', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('_type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.TextField()),
                ('_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('artistCredit', models.TextField()),
            ],
        ),
    ]
