# Generated by Django 2.2.4 on 2019-08-05 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('disambiguation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistSearch',
            fields=[
                ('alias', models.TextField()),
                ('area', models.TextField()),
                ('arid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist', models.TextField()),
                ('artistaccent', models.TextField()),
                ('begin', models.TextField()),
                ('beginarea', models.TextField()),
                ('comment', models.TextField()),
                ('country', models.TextField()),
                ('end', models.TextField()),
                ('endarea', models.TextField()),
                ('ended', models.TextField()),
                ('gender', models.TextField()),
                ('ipi', models.TextField()),
                ('sortname', models.TextField()),
                ('tag', models.TextField()),
                ('_type', models.TextField()),
            ],
        ),
    ]
